export enum Message {
  SOMETHING_WENT_WRONG = 'Something went wrong!',
  NO_DATA_FOUND = 'No data found!',
  CREATE_FAILED = 'Create failed!',
  UPDATE_FAILED = 'Update failed!',
  REMOVE_FAILED = 'Remove failed!',
  UPLOAD_FAILED = 'Upload failed!',
  BAD_REQUEST = 'Bad request!',
  ALREADY_EXISTS = 'Already exists!',
  NOT_ALLOWED_REQUEST = 'Not allowed request!',
  NOT_AUTHENTICATED = 'You are not authenticated, please login first!',
  TOKEN_NOT_EXIST = 'Bearer token is not provided!',
  ONLY_SPECIFIC_ROLES_ALLOWED = 'Allowed only for members with specific roles!',
  AGENCY_NOT_FOUND = 'Agency not found!',
  AGENCY_NOT_VERIFIED = 'Agency is not verified yet!',
  SERVICE_NOT_FOUND = 'Service not found!',
  APPLICATION_NOT_FOUND = 'Application not found!',
  USER_NOT_FOUND = 'User not found!',
  WRONG_PASSWORD = 'Wrong password, try again!',
  USED_EMAIL = 'This email is already registered!',
}
