export enum NotificationType {
  FOLLOW = 'FOLLOW',
  NEW_SERVICE = 'NEW_SERVICE',
  APPLICATION_RECEIVED = 'APPLICATION_RECEIVED',
  APPLICATION_STATUS_CHANGED = 'APPLICATION_STATUS_CHANGED',
  NEW_REVIEW = 'NEW_REVIEW',
}
